// GENERATED by scripts/build-exploded-layers.mjs — do not edit by hand.
// Re-run the script after changing the cut coordinates.

export type ExplodedLayer = {
  /** Stable key. */
  id: string;
  /** Label rendered beside the layer, in Persian. */
  title: string;
  /** Secondary line under the title. */
  note: string;
  /** clip-path polygon isolating this layer's silhouette from the shared frame. */
  clipPath: string;
  /**
   * Assembled-state offset, as a percentage of the frame height. Every layer
   * animates from this value to 0, where 0 reproduces the original render.
   * Kept small enough that a band's background never travels far enough to
   * cover the layer beneath it.
   */
  offset: number;
  /** Paint order — a layer must sit in front of whatever it occludes. */
  z: number;
  /** Vertical anchor for the HTML label, as a percentage of frame height. */
  labelAt: number;
};

export const STACK_IMAGE = {
  src: "/images/products/exploded-stack.jpg",
  width: 1270,
  height: 1330,
} as const;

export const EXPLODED_LAYERS: ExplodedLayer[] = [
  {
    id: "lid",
    title: "لایه چاپی بیرونی",
    note: "با کیفیت افست",
    clipPath:
      "polygon(0% 0%, 100% 0%, 100% 13.614%, 97.008% 13.308%, 34.803% 34.737%, 3.937% 23.534%, 0% 23.333%)",
    offset: 30.1,
    z: 50,
    labelAt: 19.5,
  },
  {
    id: "board-top",
    title: "لایه مقوا",
    note: "سخت و محکم",
    clipPath:
      "polygon(0% 23.333%, 3.937% 23.534%, 34.803% 34.737%, 97.008% 13.308%, 100% 13.614%, 100% 29.999%, 96.299% 29.699%, 36.85% 37.218%, 4.567% 32.18%, 0% 32.236%)",
    offset: 21.1,
    z: 40,
    labelAt: 33.8,
  },
  {
    id: "flute",
    title: "لایه فلوت",
    note: "جذب ضربه",
    clipPath:
      "polygon(0% 32.236%, 4.567% 32.18%, 36.85% 37.218%, 96.299% 29.699%, 100% 29.999%, 100% 43.909%, 96.299% 43.609%, 40.157% 54.737%, 7.48% 45.113%, 0% 45.296%)",
    offset: 12.4,
    z: 30,
    labelAt: 49.6,
  },
  {
    id: "tray",
    title: "لایه مقوا",
    note: "سخت و محکم",
    clipPath:
      "polygon(0% 45.296%, 7.48% 45.113%, 40.157% 54.737%, 96.299% 43.609%, 100% 43.909%, 100% 62.135%, 97.008% 61.88%, 40.945% 73.308%, 6.299% 61.504%, 0% 61.637%)",
    offset: 4.1,
    z: 20,
    labelAt: 64.7,
  },
  {
    id: "base",
    title: "لایه داخلی",
    note: "محافظ محصول",
    clipPath:
      "polygon(0% 61.637%, 6.299% 61.504%, 40.945% 73.308%, 97.008% 61.88%, 100% 62.135%, 100% 100%, 0% 100%)",
    offset: 0,
    z: 25,
    labelAt: 80.1,
  },
];
