"use client";

import { useEffect, useRef } from "react";
import gsap from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";
import HeroDebug from "./HeroDebug";
import { heroDebugState } from "./heroDebugState";
import { asset } from "@/lib/base-path";
import { INTRO_DONE } from "@/components/sections/Intro";

if (typeof window !== "undefined") {
  gsap.registerPlugin(ScrollTrigger);
}

// Generated by scripts/build-hero-frames.mjs — keep in sync with FRAME_COUNT there.
const FRAME_COUNT = 60;
const FRAME_W = 960;
const FRAME_H = 540;
const framePath = (i: number) =>
  asset(`/images/hero-frames/f_${String(i + 1).padStart(3, "0")}.jpg`);

/**
 * Hero: the carton exploding, scrubbed by scroll.
 *
 * Driven by a numbered JPEG sequence drawn to a canvas, not by a video.
 *
 * The video approach was abandoned after measuring it on an iPhone inside
 * Instagram's in-app browser — which is where this link actually gets opened.
 * Two separate platform behaviours defeated it, one stacked on the other:
 *
 *  1. Cloudflare Pages does not send `Accept-Ranges` for the file, and a
 *     browser will not seek a media resource whose origin withholds it. On
 *     desktop that produced readyState 4 and buffered [0,10] alongside
 *     seekable [0,0], so every currentTime write was silently clamped to 0.
 *     Fetching the file as a blob fixed that much.
 *  2. iOS then refused to decode the blob at all: seekable [0,10] with
 *     buffered [] after 34 seconds. Apple does not preload video data without
 *     a real play(), and muted autoplay is additionally blocked inside an
 *     in-app WebView, so there was no gesture to unlock it with.
 *
 * Images carry no such policy — and at 60 frames the sequence is 1.4 MB
 * against the video's 3.2 MB, so the robust path is also the cheaper one.
 *
 * The original clip-path implementation is still kept in ExplodedHeroLayers.tsx.
 */
export default function ExplodedHero() {
  const root = useRef<HTMLElement>(null);
  const canvas = useRef<HTMLCanvasElement>(null);
  const heading = useRef<HTMLHeadingElement>(null);

  // The headline sweeps in with the same clip-path wipe the sections use, but
  // triggered by the intro finishing rather than by scrolling — it is already
  // on screen, so a scroll trigger would never fire for it.
  useEffect(() => {
    const el = heading.current;
    if (!el) return;
    if (window.matchMedia("(prefers-reduced-motion: reduce)").matches) return;

    const play = () =>
      gsap.fromTo(
        el,
        { clipPath: "inset(0 0 100% 0)" },
        { clipPath: "inset(0 0 0% 0)", duration: 1.25, ease: "expo.out" },
      );

    // If the intro already finished before this mounted, play straight away.
    if (!document.documentElement.classList.contains("intro-active")) {
      const t = window.setTimeout(play, 80);
      return () => window.clearTimeout(t);
    }
    window.addEventListener(INTRO_DONE, play, { once: true });
    return () => window.removeEventListener(INTRO_DONE, play);
  }, []);

  useEffect(() => {
    const cv = canvas.current;
    if (!cv) return;
    const ctx = cv.getContext("2d", { alpha: false });
    if (!ctx) return;

    const frames: HTMLImageElement[] = [];
    const loaded = new Array<boolean>(FRAME_COUNT).fill(false);
    let disposed = false;
    let lastDrawn = -1;

    const startedAt = Date.now();
    heroDebugState.framesTotal = FRAME_COUNT;
    heroDebugState.framesLoaded = 0;

    // Nearest *loaded* frame at or below the target, so scrolling during the
    // download shows the closest real frame instead of freezing on frame 0 or
    // flashing blank. Falls forward if nothing below has arrived yet.
    const resolve = (want: number) => {
      for (let i = want; i >= 0; i--) if (loaded[i]) return i;
      for (let i = want + 1; i < FRAME_COUNT; i++) if (loaded[i]) return i;
      return -1;
    };

    const draw = (progress: number) => {
      const want = Math.min(
        FRAME_COUNT - 1,
        Math.max(0, Math.round(progress * (FRAME_COUNT - 1))),
      );
      const idx = resolve(want);
      if (idx < 0 || idx === lastDrawn) return;
      ctx.drawImage(frames[idx], 0, 0, cv.width, cv.height);
      lastDrawn = idx;
      heroDebugState.drawnFrame = idx;
    };

    // Progress is tracked outside the ScrollTrigger so a frame arriving late
    // can be painted at the position the visitor has already scrolled to.
    let progress = 0;

    for (let i = 0; i < FRAME_COUNT; i++) {
      const img = new Image();
      img.decoding = "async";
      img.src = framePath(i);
      img.onload = () => {
        if (disposed) return;
        loaded[i] = true;
        heroDebugState.framesLoaded += 1;
        if (heroDebugState.framesLoaded === 1)
          heroDebugState.firstFrameAtMs = Date.now() - startedAt;
        if (heroDebugState.framesLoaded === FRAME_COUNT)
          heroDebugState.allFramesAtMs = Date.now() - startedAt;
        // Repaint if this frame is a better match than what is on screen.
        const want = Math.round(progress * (FRAME_COUNT - 1));
        if (Math.abs(i - want) <= Math.abs(lastDrawn - want)) {
          lastDrawn = -1;
          draw(progress);
        }
      };
      frames[i] = img;
    }

    const mm = gsap.matchMedia(root);

    mm.add(
      {
        isDesktop: "(min-width: 1024px)",
        // Explicit mobile query on purpose. gsap.matchMedia only runs the
        // callback when at least one condition matches, so with only
        // isDesktop + reduced a phone matched nothing, the callback never ran,
        // and the hero sat frozen on its first frame with no ScrollTrigger.
        isMobile: "(max-width: 1023px)",
        reduced: "(prefers-reduced-motion: reduce)",
      },
      (context) => {
        const { isDesktop, reduced } = context.conditions as {
          isDesktop: boolean;
          isMobile: boolean;
          reduced: boolean;
        };

        const hint = root.current?.querySelector<HTMLElement>(".hero-scroll-hint");

        // Reduced motion: show the finished diagram, no pin, no scrub.
        if (reduced) {
          progress = 1;
          draw(1);
          return;
        }

        const tl = gsap.timeline({
          scrollTrigger: {
            trigger: root.current,
            start: "top top",
            // Desktop pins for 170% of the viewport. Mobile cannot pin — the
            // stacked hero is taller than the screen — so it scrubs over a
            // stretch of travel instead. Half a viewport, not a full one:
            // measured on Barry's iPhone the sequence needed ~760px of scroll
            // to finish, which is more thumb than the animation is worth and
            // left the stage drifting out of frame before it completed.
            end: isDesktop ? "+=170%" : "+=50%",
            scrub: 0.9,
            pin: isDesktop,
            onUpdate: (self) => {
              progress = self.progress;
              heroDebugState.progress = progress;
              draw(progress);
            },
          },
        });

        if (hint) tl.to(hint, { autoAlpha: 0, duration: 0.3 }, 0);
      },
    );

    return () => {
      disposed = true;
      frames.forEach((img) => {
        img.onload = null;
      });
      mm.revert();
    };
  }, []);

  return (
    <section
      ref={root}
      className="relative flex min-h-svh items-center overflow-hidden bg-bg py-16 lg:py-0"
    >
      <div className="mx-auto grid w-full max-w-[1400px] items-center gap-12 px-6 md:px-12 lg:grid-cols-[minmax(0,0.85fr)_minmax(0,1.15fr)] lg:gap-12">
        <div>
          <p className="mb-6 text-sm font-medium [word-spacing:0.6em] text-gold">
            کیهان نما ایلیا · بسته‌بندی
          </p>

          {/* One line on phones. At the display scale's 48px floor the line
              renders 336px wide against 327px available — 9px over — so below
              lg it steps down to 44px, which measures 308px and leaves room for
              iOS shaping the glyphs slightly wider. A canvas measureText
              estimate said 263px and was simply wrong: it does not reproduce
              Persian joining, so the real width has to come from layout.
              The break returns at lg, where two lines read stronger.
              `lg:inline` rather than `lg:block`: display:none suppresses a <br>,
              but only its default inline display reliably breaks the line. */}
          <h1
            ref={heading}
            data-shimmer="gold"
            className="text-display max-lg:text-[2.75rem]/[0.95] font-black"
          >
            پنج لایه{" "}
            <br className="hidden lg:inline" />
            یک جعبه
          </h1>

          <p className="mt-8 max-w-lg text-lead font-normal text-muted">
            ساختار کارتن پنج لایه فلات پسته — از مقوای خام تا خط طلایی روی درب.
            هر لایه یک کار مشخص دارد: استحکام، جذب ضربه، و محافظت از محصول تا
            رسیدن به دست مشتری.
          </p>

          <p className="hero-scroll-hint mt-10 flex items-center gap-3 text-sm text-muted">
            <span className="inline-block h-8 w-5 rounded-full border border-gold-line">
              <span className="mx-auto mt-1.5 block h-1.5 w-1 rounded-full bg-gold" />
            </span>
            {/* Only the words shimmer. The clip would otherwise take in the
                mouse glyph beside them, which is a border and a dot, not text. */}
            <span data-shimmer>اسکرول کنید تا لایه‌ها باز شوند</span>
          </p>
        </div>

        <div
          className="hero-stage relative w-full overflow-hidden rounded-[1.75rem] border border-gold-line shadow-2xl shadow-black/60"
          style={{ aspectRatio: "16 / 9", willChange: "transform" }}
        >
          {/* Frame 1 as a CSS background, so the stage is never an empty box
              between first paint and the first frame decoding. */}
          <canvas
            ref={canvas}
            width={FRAME_W}
            height={FRAME_H}
            aria-hidden="true"
            className="absolute inset-0 h-full w-full object-cover"
            style={{
              backgroundImage: `url(${asset("/images/hero-poster.jpg")})`,
              backgroundSize: "cover",
              backgroundPosition: "center",
            }}
          />

          {/* The diagram carries its own Persian layer annotations, so the
              description here is the accessible equivalent of the finished
              diagram rather than a duplicate label set. */}
          <span className="sr-only">
            نمای انفجاری کارتن پنج لایه پسته فلات: لایه چاپی بیرونی، لایه مقوا،
            لایه فلوت، لایه مقوا و لایه داخلی محافظ، همراه با ضخامت هر لایه.
          </span>
        </div>
      </div>

      {/* Renders only with ?debug=1 in the URL. */}
      <HeroDebug />
    </section>
  );
}
